package com.example.weatherapp.home.model

data class Daily( val dt: Long,
                  val sunrise: Int,
                  val sunset: Int,
                  val moonrise: Int,
                  val moonset: Int,
                  val moon_phase: Double,
                  val temp: Temp,
                  val feels_like: FeelsLike,
                  val pressure: Int,
                  val humidity: Int,
                  val dew_point: Double,
                  val wind_speed: Double ,
                  val wind_deg: Int ,
                  val weather: List<WeatherItem>,
                  val clouds: Int,
                  val pop: Double,
                  val rain: Double,
                  val uvi: Double )
